server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JeongSoonMin/spring-cloud-config.git
          search-paths: /**
          default-label: main
management:
  endpoints:
    web:
      exposure:
        include: health